version: "3"

services:
  monerod-exporter:
    image: hundehausen/monerod-exporter:latest
    container_name: monerod-exporter
    restart: unless-stopped
    build: ./
    ports:
      - 18083:18083
    environment: 
      DAEMON_HOST: http://monerod:18081
      PORT: 18083
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
        - ./prometheus/config:/etc/prometheus
        - ./prometheus/data:/prometheus
    command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/etc/prometheus/console_libraries'
        - '--web.console.templates=/etc/prometheus/consoles'
        - '--storage.tsdb.retention.time=1y'
        - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
        - 9090:9090
  grafana:
    image: grafana/grafana:latest
    container_name: monero-grafana
    volumes:
        - ./grafana/data:/var/lib/grafana
        - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=MoneroMeansMoney
    - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - 3000:3000
  monerod:
    image: hundehausen/monero-full-node:latest
    container_name: monero-full-node
    volumes:
        - ./bitmonero:/home/monero/.bitmonero
    restart: unless-stopped
    ports:
    - 18080:18080
    - 18081:18081