global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'monerod-exporter'
    scrape_interval: 30s
    static_configs:
      - targets: ['monerod-exporter:18083']